export const config = {
	port: Number(process.env.PORT || 4242),
	appName: "Auto Screen Backend",
	appOrigin: process.env.APP_ORIGIN || "https://autoscreen.app",
	pricingPath: "/pricing",
	googleAuthEnabled: process.env.GOOGLE_AUTH_ENABLED === "true",
	kakaoAuthEnabled: process.env.KAKAO_AUTH_ENABLED === "true",
	naverAuthEnabled: process.env.NAVER_AUTH_ENABLED === "true",
	tossBillingEnabled: process.env.TOSS_BILLING_ENABLED === "true",
	databaseUrl: process.env.DATABASE_URL || "",
	databaseSsl: process.env.DATABASE_SSL === "true",
	adminApiToken: process.env.ADMIN_API_TOKEN || "",
	smsProvider: process.env.SMS_PROVIDER || "solapi",
	smsSender: process.env.SMS_SENDER || "",
	smsApiKey: process.env.SMS_API_KEY || "",
	smsApiSecret: process.env.SMS_API_SECRET || "",
	smsApiBaseUrl: process.env.SMS_API_BASE_URL || "https://api.solapi.com",
	smsDryRun: process.env.SMS_DRY_RUN !== "false",
	freeTrialDays: Number(process.env.FREE_TRIAL_DAYS || 7),
	freeTrialPerPhoneLimit: Number(process.env.FREE_TRIAL_PER_PHONE_LIMIT || 1),
	freeTrialPerDeviceLimit: Number(process.env.FREE_TRIAL_PER_DEVICE_LIMIT || 1),
	phoneVerificationRequestCooldownMs: Number(
		process.env.PHONE_VERIFICATION_REQUEST_COOLDOWN_MS || 30000,
	),
	phoneVerificationCodeTtlMs: Number(process.env.PHONE_VERIFICATION_CODE_TTL_MS || 180000),
	phoneVerificationMaxAttempts: Number(process.env.PHONE_VERIFICATION_MAX_ATTEMPTS || 5),
	phoneVerificationMaxRequestsPerHour: Number(
		process.env.PHONE_VERIFICATION_MAX_REQUESTS_PER_HOUR || 5,
	),
	termsVersion: process.env.TERMS_VERSION || "2026-04-09",
	privacyVersion: process.env.PRIVACY_VERSION || "2026-04-09",
} as const;
