export {
	createProjectData,
	createProjectSnapshot,
	deriveNextId,
	type EditorProjectData,
	fromFileUrl,
	hasProjectUnsavedChanges,
	normalizeProjectEditor,
	PROJECT_VERSION,
	type ProjectEditorState,
	resolveProjectMedia,
	toFileUrl,
	validateProjectData,
	WALLPAPER_PATHS,
} from "@/shared/project-schema";
