export type { WebcamLayoutPreset } from "@/lib/compositeLayout";

export {
	type AnnotationPosition,
	type AnnotationRegion,
	type AnnotationSize,
	type AnnotationTextStyle,
	type AnnotationType,
	type ArrowDirection,
	type BlurData,
	type BlurShape,
	type CropRegion,
	type CursorTelemetryPoint,
	clampFocusToDepth,
	clampPlaybackSpeed,
	DEFAULT_ANNOTATION_POSITION,
	DEFAULT_ANNOTATION_SIZE,
	DEFAULT_ANNOTATION_STYLE,
	DEFAULT_BLUR_DATA,
	DEFAULT_BLUR_FREEHAND_POINTS,
	DEFAULT_BLUR_INTENSITY,
	DEFAULT_CROP_REGION,
	DEFAULT_FIGURE_DATA,
	DEFAULT_PLAYBACK_SPEED,
	DEFAULT_WEBCAM_LAYOUT_PRESET,
	DEFAULT_WEBCAM_MASK_SHAPE,
	DEFAULT_WEBCAM_POSITION,
	DEFAULT_WEBCAM_SIZE_PRESET,
	DEFAULT_ZOOM_DEPTH,
	type FigureData,
	MAX_BLUR_INTENSITY,
	MAX_PLAYBACK_SPEED,
	MIN_BLUR_INTENSITY,
	MIN_PLAYBACK_SPEED,
	type PlaybackSpeed,
	SPEED_OPTIONS,
	type SpeedRegion,
	type TrimRegion,
	type WebcamMaskShape,
	type WebcamPosition,
	type WebcamSizePreset,
	ZOOM_DEPTH_SCALES,
	type ZoomDepth,
	type ZoomFocus,
	type ZoomFocusMode,
	type ZoomRegion,
} from "@/shared/types";
